language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

before_install:
  - cd ${TRAVIS_HOME}/web-components

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: build
  on:
    branch:
      - master
      - devel
